<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Styles [
<!ELEMENT Styles (Style+)>
<!ELEMENT Style (Attribute)>
<!ATTLIST Style name CDATA #REQUIRED>
<!ATTLIST Style element CDATA #REQUIRED>
<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute name CDATA #REQUIRED>
<!ATTLIST Attribute value CDATA #REQUIRED>
]>
<!--
 * File Name: phpwsstyles.xml
 * This is a custom style file for phpWebSite. It is based on
 * fckstyles.xml by Frederico Caldeira Knabben (fredck@fckeditor.net)
 *
 * File Authors:
 *      Matthew McNaney <mcnaney at gmail dot com>
-->
<Styles>
    <Style name="Clear left" element="p">
        <Attribute name="style" value="clear : left" />
    </Style>
    <Style name="Clear right" element="p">
        <Attribute name="style" value="clear : right" />
    </Style>
    <Style name="Image on Left" element="img">
        <Attribute name="class" value="float-left" />
    </Style>
    <Style name="Image on Right" element="img">
        <Attribute name="class" value="float-right" />
    </Style>
    <Style name="Smaller" element="span">
        <Attribute name="class" value="smaller" />
    </Style>
    <Style name="Larger" element="span">
        <Attribute name="class" value="larger" />
    </Style>
</Styles>
